export type Language = 'mr' | 'hi' | 'en' | 'kn';

export interface MenuItem {
  id: string;
  category: 'THALI' | 'STARTERS' | 'MAIN_COURSE' | 'BREADS' | 'RICE' | 'BEVERAGES' | 'SNACKS';
  price: number;
  is_veg: boolean;
  is_available: boolean;
  image_url: string;
  name_mr: string; name_hi: string; name_en: string; name_kn: string;
  description_mr: string; description_hi: string; description_en: string; description_kn: string;
}

export const menuData: MenuItem[] = [
  // ===== THALI =====
  {
    id: 'thali-001',
    category: 'THALI',
    price: 150,
    is_veg: true,
    is_available: true,
    image_url: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=400&q=80',
    name_mr: 'व्हेज रेग्युलर फ्युजन चपाती थाळी',
    name_hi: 'वेज रेगुलर फ्यूजन चपाती थाली',
    name_en: 'Veg Regular Fusion Chapati Thali',
    name_kn: 'ವೆಜ್ ರೆಗ್ಯುಲರ್ ಫ್ಯೂಷನ್ ಚಪಾತಿ ಥಾಲಿ',
    description_mr: 'चपाती, भाजी, वरण, भात, लोणचे आणि सलाड यांसह संपूर्ण शाकाहारी थाळी',
    description_hi: 'चपाती, सब्जी, दाल, चावल, अचार और सलाद के साथ पूरी शाकाहारी थाली',
    description_en: 'Complete veg thali with chapati, sabzi, dal, rice, pickle and salad',
    description_kn: 'ಚಪಾತಿ, ತರಕಾರಿ, ಬೇಳೆ, ಅನ್ನ, ಉಪ್ಪಿನಕಾಯಿ ಮತ್ತು ಸಲಾಡ್ ಸಹಿತ ಪೂರ್ಣ ಶಾಕಾಹಾರಿ ಥಾಲಿ',
  },
  {
    id: 'thali-002',
    category: 'THALI',
    price: 180,
    is_veg: true,
    is_available: true,
    image_url: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=400&q=80',
    name_mr: 'व्हेज स्पेशल फ्युजन भाकरी थाळी',
    name_hi: 'वेज स्पेशल फ्यूजन भाकरी थाली',
    name_en: 'Veg Special Fusion Bhakri Thali',
    name_kn: 'ವೆಜ್ ಸ್ಪೆಷಲ್ ಫ್ಯೂಷನ್ ಭಾಕ್ರಿ ಥಾಲಿ',
    description_mr: 'ज्वारी भाकरी, पिठले, ठेचा, भात, वरण आणि ताक यांसह खास थाळी',
    description_hi: 'ज्वारी भाकरी, पिठले, ठेचा, चावल, दाल और छाछ के साथ विशेष थाली',
    description_en: 'Special thali with jowar bhakri, pithle, thecha, rice, dal and buttermilk',
    description_kn: 'ಜ್ವಾರಿ ಭಾಕ್ರಿ, ಪಿಠ್ಲೆ, ಠೇಚಾ, ಅನ್ನ, ಬೇಳೆ ಮತ್ತು ಮಜ್ಜಿಗೆ ಸಹಿತ ವಿಶೇಷ ಥಾಲಿ',
  },
  {
    id: 'thali-003',
    category: 'THALI',
    price: 200,
    is_veg: false,
    is_available: true,
    image_url: 'https://images.unsplash.com/photo-1482049016688-2d3e1b311543?w=400&q=80',
    name_mr: 'एग मसाला थाळी विथ चपाती',
    name_hi: 'एग मसाला थाली विथ चपाती',
    name_en: 'Egg Masala Thali with Chapati',
    name_kn: 'ಎಗ್ ಮಸಾಲಾ ಥಾಲಿ ವಿತ್ ಚಪಾತಿ',
    description_mr: 'मसालेदार अंडा करी, चपाती, भात, वरण आणि सलाड सहित',
    description_hi: 'मसालेदार अंडा करी, चपाती, चावल, दाल और सलाद के साथ',
    description_en: 'Spicy egg masala curry served with chapati, rice, dal and salad',
    description_kn: 'ಮಸಾಲಾ ಮೊಟ್ಟೆ ಕರಿ, ಚಪಾತಿ, ಅನ್ನ, ಬೇಳೆ ಮತ್ತು ಸಲಾಡ್ ಸಹಿತ',
  },
  {
    id: 'thali-004',
    category: 'THALI',
    price: 250,
    is_veg: false,
    is_available: true,
    image_url: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=400&q=80',
    name_mr: 'चिकन फ्राय थाळी विथ भाकरी',
    name_hi: 'चिकन फ्राय थाली विथ भाकरी',
    name_en: 'Chicken Fry Thali with Bhakri',
    name_kn: 'ಚಿಕನ್ ಫ್ರೈ ಥಾಲಿ ವಿತ್ ಭಾಕ್ರಿ',
    description_mr: 'कुरकुरीत चिकन फ्राय, भाकरी, पांढरा रस्सा, भात आणि ताक सहित',
    description_hi: 'कुरकुरा चिकन फ्राय, भाकरी, पांढरा रस्सा, चावल और छाछ के साथ',
    description_en: 'Crispy chicken fry with bhakri, pandhra rassa, rice and buttermilk',
    description_kn: 'ಕ್ರಿಸ್ಪಿ ಚಿಕನ್ ಫ್ರೈ, ಭಾಕ್ರಿ, ಪಾಂಧ್ರಾ ರಸ್ಸಾ, ಅನ್ನ ಮತ್ತು ಮಜ್ಜಿಗೆ ಸಹಿತ',
  },
  {
    id: 'thali-005',
    category: 'THALI',
    price: 250,
    is_veg: false,
    is_available: true,
    image_url: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=400&q=80',
    name_mr: 'चिकन फ्राय थाळी विथ चपाती',
    name_hi: 'चिकन फ्राय थाली विथ चपाती',
    name_en: 'Chicken Fry Thali with Chapati',
    name_kn: 'ಚಿಕನ್ ಫ್ರೈ ಥಾಲಿ ವಿತ್ ಚಪಾತಿ',
    description_mr: 'कुरकुरीत चिकन फ्राय, चपाती, पांढरा रस्सा, भात आणि सलाड सहित',
    description_hi: 'कुरकुरा चिकन फ्राय, चपाती, पांढरा रस्सा, चावल और सलाद के साथ',
    description_en: 'Crispy chicken fry with chapati, pandhra rassa, rice and salad',
    description_kn: 'ಕ್ರಿಸ್ಪಿ ಚಿಕನ್ ಫ್ರೈ, ಚಪಾತಿ, ಪಾಂಧ್ರಾ ರಸ್ಸಾ, ಅನ್ನ ಮತ್ತು ಸಲಾಡ್ ಸಹಿತ',
  },
  {
    id: 'thali-006',
    category: 'THALI',
    price: 300,
    is_veg: false,
    is_available: true,
    image_url: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d6?w=400&q=80',
    name_mr: 'मटण फ्राय थाळी',
    name_hi: 'मटन फ्राय थाली',
    name_en: 'Mutton Fry Thali',
    name_kn: 'ಮಟನ್ ಫ್ರೈ ಥಾಲಿ',
    description_mr: 'खमंग मटण फ्राय, भाकरी / चपाती, तांबडा रस्सा, भात, वरण, ताक सहित',
    description_hi: 'स्वादिष्ट मटन फ्राय, भाकरी / चपाती, तांबडा रस्सा, चावल, दाल, छाछ के साथ',
    description_en: 'Flavourful mutton fry with bhakri/chapati, tambda rassa, rice, dal and buttermilk',
    description_kn: 'ರುಚಿಕರ ಮಟನ್ ಫ್ರೈ, ಭಾಕ್ರಿ/ಚಪಾತಿ, ತಾಂಬ್ಡಾ ರಸ್ಸಾ, ಅನ್ನ, ಬೇಳೆ ಮತ್ತು ಮಜ್ಜಿಗೆ ಸಹಿತ',
  },
  {
    id: 'thali-007',
    category: 'THALI',
    price: 350,
    is_veg: false,
    is_available: true,
    image_url: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=400&q=80',
    name_mr: 'स्पेशल नॉन-व्हेज थाळी',
    name_hi: 'स्पेशल नॉन-वेज थाली',
    name_en: 'Special Non-Veg Thali',
    name_kn: 'ಸ್ಪೆಷಲ್ ನಾನ್-ವೆಜ್ ಥಾಲಿ',
    description_mr: 'चिकन + मटण फ्राय, भाकरी, तांबडा/पांढरा रस्सा, भात, वरण, ताक, सलाड सहित',
    description_hi: 'चिकन + मटन फ्राय, भाकरी, तांबडा/पांढरा रस्सा, चावल, दाल, छाछ, सलाद के साथ',
    description_en: 'Premium thali with chicken + mutton fry, bhakri, both rassas, rice, dal and buttermilk',
    description_kn: 'ಚಿಕನ್ + ಮಟನ್ ಫ್ರೈ, ಭಾಕ್ರಿ, ತಾಂಬ್ಡಾ/ಪಾಂಧ್ರಾ ರಸ್ಸಾ, ಅನ್ನ, ಬೇಳೆ ಮತ್ತು ಮಜ್ಜಿಗೆ ಸಹಿತ ಪ್ರೀಮಿಯಮ್ ಥಾಲಿ',
  },
  {
    id: 'thali-008',
    category: 'THALI',
    price: 320,
    is_veg: false,
    is_available: true,
    image_url: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=400&q=80',
    name_mr: 'मटण कीमा थाळी',
    name_hi: 'मटन कीमा थाली',
    name_en: 'Mutton Keema Thali',
    name_kn: 'ಮಟನ್ ಕೀಮಾ ಥಾಲಿ',
    description_mr: 'मसालेदार मटण कीमा, भाकरी / चपाती, भात, वरण, ताक आणि सलाड सहित',
    description_hi: 'मसालेदार मटन कीमा, भाकरी / चपाती, चावल, दाल, छाछ और सलाद के साथ',
    description_en: 'Spiced mutton keema with bhakri/chapati, rice, dal, buttermilk and salad',
    description_kn: 'ಮಸಾಲೆ ಮಟನ್ ಕೀಮಾ, ಭಾಕ್ರಿ/ಚಪಾತಿ, ಅನ್ನ, ಬೇಳೆ, ಮಜ್ಜಿಗೆ ಮತ್ತು ಸಲಾಡ್ ಸಹಿತ',
  },
  {
    id: 'thali-009',
    category: 'THALI',
    price: 350,
    is_veg: false,
    is_available: true,
    image_url: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d6?w=400&q=80',
    name_mr: 'अलानी मटण थाळी',
    name_hi: 'अलानी मटन थाली',
    name_en: 'Alani Mutton Thali',
    name_kn: 'ಅಲಾನಿ ಮಟನ್ ಥಾಲಿ',
    description_mr: 'आमची प्रसिद्ध अलानी मटण करी, भाकरी, तांबडा रस्सा, भात, वरण आणि ताक सहित',
    description_hi: 'हमारी प्रसिद्ध अलानी मटन करी, भाकरी, तांबडा रस्सा, चावल, दाल और छाछ के साथ',
    description_en: 'Our signature alani mutton curry with bhakri, tambda rassa, rice, dal and buttermilk',
    description_kn: 'ನಮ್ಮ ಸಿಗ್ನೇಚರ್ ಅಲಾನಿ ಮಟನ್ ಕರಿ, ಭಾಕ್ರಿ, ತಾಂಬ್ಡಾ ರಸ್ಸಾ, ಅನ್ನ, ಬೇಳೆ ಮತ್ತು ಮಜ್ಜಿಗೆ ಸಹಿತ',
  },
  {
    id: 'thali-010',
    category: 'THALI',
    price: 300,
    is_veg: false,
    is_available: true,
    image_url: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=400&q=80',
    name_mr: 'अलानी चिकन थाळी',
    name_hi: 'अलानी चिकन थाली',
    name_en: 'Alani Chicken Thali',
    name_kn: 'ಅಲಾನಿ ಚಿಕನ್ ಥಾಲಿ',
    description_mr: 'आमची खास अलानी चिकन करी, भाकरी, पांढरा रस्सा, भात, वरण आणि ताक सहित',
    description_hi: 'हमारी खास अलानी चिकन करी, भाकरी, पांढरा रस्सा, चावल, दाल और छाछ के साथ',
    description_en: 'Our special alani chicken curry with bhakri, pandhra rassa, rice, dal and buttermilk',
    description_kn: 'ನಮ್ಮ ವಿಶೇಷ ಅಲಾನಿ ಚಿಕನ್ ಕರಿ, ಭಾಕ್ರಿ, ಪಾಂಧ್ರಾ ರಸ್ಸಾ, ಅನ್ನ, ಬೇಳೆ ಮತ್ತು ಮಜ್ಜಿಗೆ ಸಹಿತ',
  },
  // ===== STARTERS =====
  {
    id: 'starter-001',
    category: 'STARTERS',
    price: 190,
    is_veg: false,
    is_available: true,
    image_url: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d6?w=400&q=80',
    name_mr: 'मटण कीमा',
    name_hi: 'मटन कीमा',
    name_en: 'Mutton Keema',
    name_kn: 'ಮಟನ್ ಕೀಮಾ',
    description_mr: 'महाराष्ट्रीयन मसाल्यांनी तयार केलेला रुचकर मटण कीमा',
    description_hi: 'महाराष्ट्रीयन मसालों से बना स्वादिष्ट मटन कीमा',
    description_en: 'Flavourful mutton keema prepared with authentic Maharashtrian spices',
    description_kn: 'ಅಸಲಿ ಮಹಾರಾಷ್ಟ್ರೀಯ ಮಸಾಲೆಗಳಿಂದ ತಯಾರಿಸಿದ ರುಚಿಕರ ಮಟನ್ ಕೀಮಾ',
  },
  {
    id: 'starter-002',
    category: 'STARTERS',
    price: 200,
    is_veg: false,
    is_available: true,
    image_url: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d6?w=400&q=80',
    name_mr: 'अलानी मटण',
    name_hi: 'अलानी मटन',
    name_en: 'Alani Mutton',
    name_kn: 'ಅಲಾನಿ ಮಟನ್',
    description_mr: 'थाली हाऊसची खास अलानी पद्धतीने शिजवलेले मटण',
    description_hi: 'थाली हाउस की खास अलानी विधि से पकाया हुआ मटन',
    description_en: "Thali House's signature mutton prepared in the special alani style",
    description_kn: 'ಥಾಲಿ ಹೌಸ್‌ನ ವಿಶೇಷ ಅಲಾನಿ ಶೈಲಿಯಲ್ಲಿ ಬೇಯಿಸಿದ ಮಟನ್',
  },
  // ===== MAIN COURSE =====
  {
    id: 'main-001',
    category: 'MAIN_COURSE',
    price: 220,
    is_veg: false,
    is_available: true,
    image_url: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=400&q=80',
    name_mr: 'अलानी चिकन',
    name_hi: 'अलानी चिकन',
    name_en: 'Alani Chicken',
    name_kn: 'ಅಲಾನಿ ಚಿಕನ್',
    description_mr: 'थाली हाऊसची खास अलानी पद्धतीने शिजवलेले चिकन',
    description_hi: 'थाली हाउस की खास अलानी विधि से पकाया हुआ चिकन',
    description_en: "Thali House's signature chicken in special alani gravy",
    description_kn: 'ಥಾಲಿ ಹೌಸ್‌ನ ವಿಶೇಷ ಅಲಾನಿ ಗ್ರೇವಿಯಲ್ಲಿ ಚಿಕನ್',
  },
  {
    id: 'main-002',
    category: 'MAIN_COURSE',
    price: 200,
    is_veg: false,
    is_available: true,
    image_url: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=400&q=80',
    name_mr: 'चिकन मसाला',
    name_hi: 'चिकन मसाला',
    name_en: 'Chicken Masala',
    name_kn: 'ಚಿಕನ್ ಮಸಾಲಾ',
    description_mr: 'दाट मसाल्याच्या ग्रेव्हीमध्ये शिजवलेले टेंडर चिकन',
    description_hi: 'घनी मसाला ग्रेवी में पकाया हुआ नरम चिकन',
    description_en: 'Tender chicken cooked in rich masala gravy with aromatic spices',
    description_kn: 'ಸಮೃದ್ಧ ಮಸಾಲಾ ಗ್ರೇವಿಯಲ್ಲಿ ಬೇಯಿಸಿದ ಮೃದು ಚಿಕನ್',
  },
  {
    id: 'main-003',
    category: 'MAIN_COURSE',
    price: 250,
    is_veg: false,
    is_available: true,
    image_url: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d6?w=400&q=80',
    name_mr: 'मटण मसाला',
    name_hi: 'मटन मसाला',
    name_en: 'Mutton Masala',
    name_kn: 'ಮಟನ್ ಮಸಾಲಾ',
    description_mr: 'मेटी मसाल्याच्या ग्रेव्हीमध्ये मंद आचेवर शिजवलेले मटण',
    description_hi: 'मेटी मसाला ग्रेवी में धीमी आंच पर पका हुआ मटन',
    description_en: 'Slow-cooked mutton in methi masala gravy with whole spices',
    description_kn: 'ಮೇಥಿ ಮಸಾಲಾ ಗ್ರೇವಿಯಲ್ಲಿ ನಿಧಾನವಾಗಿ ಬೇಯಿಸಿದ ಮಟನ್',
  },
  {
    id: 'main-004',
    category: 'MAIN_COURSE',
    price: 160,
    is_veg: false,
    is_available: true,
    image_url: 'https://images.unsplash.com/photo-1482049016688-2d3e1b311543?w=400&q=80',
    name_mr: 'एग मसाला',
    name_hi: 'एग मसाला',
    name_en: 'Egg Masala',
    name_kn: 'ಎಗ್ ಮಸಾಲಾ',
    description_mr: 'मसालेदार टोमॅटो प्याज ग्रेव्हीमध्ये उकडलेली अंडी',
    description_hi: 'मसालेदार टमाटर-प्याज ग्रेवी में उबले हुए अंडे',
    description_en: 'Boiled eggs in spicy tomato-onion masala gravy',
    description_kn: 'ಮಸಾಲಾ ಟೊಮ್ಯಾಟೊ-ಈರುಳ್ಳಿ ಗ್ರೇವಿಯಲ್ಲಿ ಬೇಯಿಸಿದ ಮೊಟ್ಟೆ',
  },
  {
    id: 'main-005',
    category: 'MAIN_COURSE',
    price: 80,
    is_veg: false,
    is_available: true,
    image_url: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=400&q=80',
    name_mr: 'तांबडा रस्सा',
    name_hi: 'तांबडा रस्सा',
    name_en: 'Tambda Rassa',
    name_kn: 'ತಾಂಬ್ಡಾ ರಸ್ಸಾ',
    description_mr: 'कोल्हापूरी पद्धतीचा तिखट तांबडा चिकन/मटण रस्सा',
    description_hi: 'कोल्हापुरी शैली का तीखा लाल चिकन/मटन रस्सा',
    description_en: 'Spicy Kolhapuri-style red chicken/mutton broth',
    description_kn: 'ಕೊಲ್ಹಾಪುರಿ ಶೈಲಿಯ ಖಾರ ಕೆಂಪು ಚಿಕನ್/ಮಟನ್ ಸಾರು',
  },
  {
    id: 'main-006',
    category: 'MAIN_COURSE',
    price: 80,
    is_veg: false,
    is_available: true,
    image_url: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=400&q=80',
    name_mr: 'पांढरा रस्सा',
    name_hi: 'पांढरा रस्सा',
    name_en: 'Pandhra Rassa',
    name_kn: 'ಪಾಂಧ್ರಾ ರಸ್ಸಾ',
    description_mr: 'नारळाच्या दुधाचा सौम्य आणि सुगंधी पांढरा रस्सा',
    description_hi: 'नारियल के दूध का हल्का और सुगंधित सफेद रस्सा',
    description_en: 'Mild and aromatic white broth made with coconut milk',
    description_kn: 'ತೆಂಗಿನ ಹಾಲಿನಿಂದ ತಯಾರಿಸಿದ ಸೌಮ್ಯ ಮತ್ತು ಸುಗಂಧಿತ ಬಿಳಿ ಸಾರು',
  },
  {
    id: 'main-007',
    category: 'MAIN_COURSE',
    price: 220,
    is_veg: false,
    is_available: true,
    image_url: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=400&q=80',
    name_mr: 'चिकन फ्राय',
    name_hi: 'चिकन फ्राय',
    name_en: 'Chicken Fry',
    name_kn: 'ಚಿಕನ್ ಫ್ರೈ',
    description_mr: 'महाराष्ट्रीयन मसाल्यात मॅरीनेट केलेले कुरकुरीत चिकन फ्राय',
    description_hi: 'महाराष्ट्रीयन मसालों में मैरीनेट किया हुआ कुरकुरा चिकन फ्राय',
    description_en: 'Crispy chicken marinated in Maharashtrian spices and shallow fried',
    description_kn: 'ಮಹಾರಾಷ್ಟ್ರೀಯ ಮಸಾಲೆಯಲ್ಲಿ ಮ್ಯಾರಿನೇಟ್ ಮಾಡಿ ಫ್ರೈ ಮಾಡಿದ ಕ್ರಿಸ್ಪಿ ಚಿಕನ್',
  },
  // ===== BREADS =====
  {
    id: 'bread-001',
    category: 'BREADS',
    price: 25,
    is_veg: true,
    is_available: true,
    image_url: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400&q=80',
    name_mr: 'चपाती',
    name_hi: 'चपाती',
    name_en: 'Chapati',
    name_kn: 'ಚಪಾತಿ',
    description_mr: 'गव्हाच्या पिठापासून बनवलेली मऊ आणि ताजी चपाती',
    description_hi: 'गेहूं के आटे से बनी मुलायम और ताजी चपाती',
    description_en: 'Soft and fresh whole wheat chapati made to order',
    description_kn: 'ಗೋಧಿ ಹಿಟ್ಟಿನಿಂದ ತಯಾರಿಸಿದ ಮೃದು ಮತ್ತು ತಾಜಾ ಚಪಾತಿ',
  },
  {
    id: 'bread-002',
    category: 'BREADS',
    price: 25,
    is_veg: true,
    is_available: true,
    image_url: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400&q=80',
    name_mr: 'भाकरी',
    name_hi: 'भाकरी',
    name_en: 'Bhakri',
    name_kn: 'ಭಾಕ್ರಿ',
    description_mr: 'ज्वारी किंवा बाजरीच्या पिठापासून बनवलेली पारंपारिक भाकरी',
    description_hi: 'ज्वारी या बाजरी के आटे से बनी पारंपरिक भाकरी',
    description_en: 'Traditional bhakri made from jowar or bajra flour',
    description_kn: 'ಜ್ವಾರಿ ಅಥವಾ ಬಜ್ರಾ ಹಿಟ್ಟಿನಿಂದ ತಯಾರಿಸಿದ ಸಾಂಪ್ರದಾಯಿಕ ಭಾಕ್ರಿ',
  },
  // ===== RICE =====
  {
    id: 'rice-001',
    category: 'RICE',
    price: 60,
    is_veg: true,
    is_available: true,
    image_url: 'https://images.unsplash.com/photo-1536304993881-ff86e0c9e6d7?w=400&q=80',
    name_mr: 'वाफवलेला भात',
    name_hi: 'उबला चावल',
    name_en: 'Steamed Rice',
    name_kn: 'ಬೇಯಿಸಿದ ಅನ್ನ',
    description_mr: 'ताजा शिजवलेला मऊ आणि सुगंधी भात',
    description_hi: 'ताज़ा पका हुआ नरम और सुगंधित चावल',
    description_en: 'Freshly cooked soft and fragrant steamed rice',
    description_kn: 'ತಾಜಾ ಬೇಯಿಸಿದ ಮೃದು ಮತ್ತು ಸುಗಂಧಿತ ಅನ್ನ',
  },
  // ===== BEVERAGES =====
  {
    id: 'bev-001',
    category: 'BEVERAGES',
    price: 30,
    is_veg: true,
    is_available: true,
    image_url: 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=400&q=80',
    name_mr: 'मसाला ताक',
    name_hi: 'मसाला छाछ',
    name_en: 'Masala Buttermilk',
    name_kn: 'ಮಸಾಲಾ ಮಜ್ಜಿಗೆ',
    description_mr: 'मसाले आणि कोथिंबीर घातलेले थंडगार मसाला ताक',
    description_hi: 'मसालों और धनिया से बनी ठंडी मसाला छाछ',
    description_en: 'Chilled buttermilk spiced with cumin, green chili and fresh coriander',
    description_kn: 'ಜೀರಿಗೆ, ಹಸಿರು ಮೆಣಸಿನಕಾಯಿ ಮತ್ತು ತಾಜಾ ಕೊತ್ತಂಬರಿ ಹಾಕಿದ ತಣ್ಣನೆ ಮಜ್ಜಿಗೆ',
  },
  {
    id: 'bev-002',
    category: 'BEVERAGES',
    price: 35,
    is_veg: true,
    is_available: true,
    image_url: 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=400&q=80',
    name_mr: 'सोलकढी',
    name_hi: 'सोलकढी',
    name_en: 'Solkadhi',
    name_kn: 'ಸೋಲ್‌ಕಢಿ',
    description_mr: 'कोकम आणि नारळाच्या दुधापासून बनवलेली पारंपारिक सोलकढी',
    description_hi: 'कोकम और नारियल के दूध से बनी पारंपरिक सोलकढी',
    description_en: 'Traditional Konkani drink made with kokum and coconut milk',
    description_kn: 'ಕೊಕಮ್ ಮತ್ತು ತೆಂಗಿನ ಹಾಲಿನಿಂದ ತಯಾರಿಸಿದ ಸಾಂಪ್ರದಾಯಿಕ ಸೋಲ್‌ಕಢಿ',
  },
  {
    id: 'bev-003',
    category: 'BEVERAGES',
    price: 25,
    is_veg: true,
    is_available: true,
    image_url: 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=400&q=80',
    name_mr: 'ताक',
    name_hi: 'छाछ',
    name_en: 'Buttermilk',
    name_kn: 'ಮಜ್ಜಿಗೆ',
    description_mr: 'ताजे दह्यापासून बनवलेले सौम्य आणि थंडगार ताक',
    description_hi: 'ताज़े दही से बनी हल्की और ठंडी छाछ',
    description_en: 'Simple and refreshing plain buttermilk made from fresh curd',
    description_kn: 'ತಾಜಾ ಮೊಸರಿನಿಂದ ತಯಾರಿಸಿದ ಸರಳ ಮತ್ತು ರಿಫ್ರೆಶಿಂಗ್ ಮಜ್ಜಿಗೆ',
  },
  // ===== SNACKS =====
  {
    id: 'snack-001',
    category: 'SNACKS',
    price: 40,
    is_veg: true,
    is_available: true,
    image_url: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=400&q=80',
    name_mr: 'मसाला पापड',
    name_hi: 'मसाला पापड',
    name_en: 'Masala Papad',
    name_kn: 'ಮಸಾಲಾ ಪಾಪಡ',
    description_mr: 'कांदा, टोमॅटो, कोथिंबीर आणि मसाल्यांनी सजवलेला कुरकुरीत पापड',
    description_hi: 'प्याज, टमाटर, धनिया और मसालों से सजा कुरकुरा पापड',
    description_en: 'Crispy roasted papad topped with onion, tomato and fresh spices',
    description_kn: 'ಈರುಳ್ಳಿ, ಟೊಮ್ಯಾಟೊ ಮತ್ತು ತಾಜಾ ಮಸಾಲೆ ಹಾಕಿದ ಕ್ರಿಸ್ಪಿ ಪಾಪಡ',
  },
];

export function getItemName(item: MenuItem, lang: Language): string {
  return item[`name_${lang}` as `name_${Language}`] ?? item.name_en;
}

export function getItemDescription(item: MenuItem, lang: Language): string {
  return item[`description_${lang}` as `description_${Language}`] ?? item.description_en;
}
