export type Language = 'mr' | 'en';

export interface MenuItem {
  id: string;
  category: 'VEG' | 'CHICKEN_THALI' | 'MUTTON_THALI' | 'HANDI' | 'EGG' | 'RICE' | 'BREADS' | 'OTHERS';
  price: number;
  is_veg: boolean;
  is_available: boolean;
  image_url: string;
  name_mr: string; name_en: string;
  description_mr: string; description_en: string;
}

export const menuData: MenuItem[] = [
  // ===== VEG =====
  { id: 'veg-001', category: 'VEG', price: 220, is_veg: true, is_available: true,
    image_url: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=400&q=80',
    name_mr: 'पनीर मसाला', name_en: 'Paneer Masala',
    description_mr: 'दाट मसाल्याच्या ग्रेव्हीमध्ये शिजवलेला ताजा पनीर',
    description_en: 'Fresh paneer in rich masala gravy' },
  { id: 'veg-002', category: 'VEG', price: 230, is_veg: true, is_available: true,
    image_url: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=400&q=80',
    name_mr: 'पनीर बटर मसाला', name_en: 'Paneer Butter Masala',
    description_mr: 'बटर आणि क्रीमयुक्त मखमली ग्रेव्हीमध्ये पनीर',
    description_en: 'Paneer in creamy butter-tomato gravy' },
  { id: 'veg-003', category: 'VEG', price: 220, is_veg: true, is_available: true,
    image_url: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=400&q=80',
    name_mr: 'काजू मसाला', name_en: 'Cashew Masala',
    description_mr: 'काजूच्या समृद्ध ग्रेव्हीमध्ये शिजवलेला खास मसाला',
    description_en: 'Rich cashew gravy with aromatic spices' },
  { id: 'veg-004', category: 'VEG', price: 250, is_veg: true, is_available: true,
    image_url: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=400&q=80',
    name_mr: 'काजू पनीर मसाला', name_en: 'Cashew Paneer Masala',
    description_mr: 'काजू आणि पनीरचा खास मसाल्यासह संगम',
    description_en: 'Cashews and paneer in special masala gravy' },
  { id: 'veg-005', category: 'VEG', price: 230, is_veg: true, is_available: true,
    image_url: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=400&q=80',
    name_mr: 'पनीर चिंगारी', name_en: 'Paneer Chingari',
    description_mr: 'तिखट मसाल्यांनी तयार केलेला झणझणीत पनीर',
    description_en: 'Spicy paneer with fiery Maharashtrian spices' },
  { id: 'veg-006', category: 'VEG', price: 240, is_veg: true, is_available: true,
    image_url: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=400&q=80',
    name_mr: 'पनीर चटपटा', name_en: 'Paneer Chatpata',
    description_mr: 'चटपटे मसाले आणि ताज्या हर्ब्ससह पनीर',
    description_en: 'Tangy and spicy paneer with chatpata masala' },
  { id: 'veg-007', category: 'VEG', price: 250, is_veg: true, is_available: true,
    image_url: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=400&q=80',
    name_mr: 'पनीर मालवणी', name_en: 'Paneer Malvani',
    description_mr: 'मालवणी मसाल्यांच्या ग्रेव्हीमध्ये शिजवलेला पनीर',
    description_en: 'Paneer in authentic Malvani coconut-spice gravy' },
  { id: 'veg-008', category: 'VEG', price: 240, is_veg: true, is_available: true,
    image_url: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=400&q=80',
    name_mr: 'पनीर तुफानी', name_en: 'Cheese Storm (Paneer Tufani)',
    description_mr: 'तुफानी मसाल्यांनी तयार केलेला झणझणीत पनीर',
    description_en: 'Bold and fiery paneer with storm of spices' },
  { id: 'veg-009', category: 'VEG', price: 250, is_veg: true, is_available: true,
    image_url: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=400&q=80',
    name_mr: 'काजू पनीर तुफानी', name_en: 'Cashew Cheese Storm',
    description_mr: 'काजू आणि पनीरचा तुफानी मसाल्यांसह संगम',
    description_en: 'Fiery combo of cashews and paneer with storm spices' },
  { id: 'veg-010', category: 'VEG', price: 200, is_veg: true, is_available: true,
    image_url: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=400&q=80',
    name_mr: 'शाकाहारी थाळी', name_en: 'Vegetarian Thali',
    description_mr: 'भाजी, वरण, भात, रोटी, लोणचे यांसह संपूर्ण थाळी',
    description_en: 'Complete veg thali with sabzi, dal, rice, roti and pickle' },
  { id: 'veg-011', category: 'VEG', price: 160, is_veg: true, is_available: true,
    image_url: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=400&q=80',
    name_mr: 'मिक्स व्हेज', name_en: 'Mix Veg',
    description_mr: 'ताज्या भाज्यांचे मसालेदार मिश्रण',
    description_en: 'Seasonal mixed vegetables in spiced gravy' },
  { id: 'veg-012', category: 'VEG', price: 180, is_veg: true, is_available: true,
    image_url: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=400&q=80',
    name_mr: 'व्हेज कोल्हापुरी', name_en: 'Veg Kolhapuri',
    description_mr: 'कोल्हापूरच्या मसाल्यांनी बनवलेली तिखट भाजी',
    description_en: 'Spicy vegetables in fiery Kolhapuri masala' },
  { id: 'veg-013', category: 'VEG', price: 220, is_veg: true, is_available: true,
    image_url: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=400&q=80',
    name_mr: 'व्हेज मालवणी', name_en: 'Veg Malvani',
    description_mr: 'नारळाच्या मालवणी मसाल्यात शिजवलेल्या भाज्या',
    description_en: 'Vegetables in coconut-based Malvani masala' },
  { id: 'veg-014', category: 'VEG', price: 120, is_veg: true, is_available: true,
    image_url: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=400&q=80',
    name_mr: 'डाळ तडका', name_en: 'Dal Tadka',
    description_mr: 'तुपाच्या तडक्यासह तयार केलेली रुचकर डाळ',
    description_en: 'Yellow dal tempered with ghee and spices' },
  { id: 'veg-015', category: 'VEG', price: 100, is_veg: true, is_available: true,
    image_url: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=400&q=80',
    name_mr: 'डाळ फ्राय', name_en: 'Dal Fry',
    description_mr: 'कांदा, टोमॅटो आणि मसाल्यांनी फ्राय केलेली डाळ',
    description_en: 'Dal fried with onion, tomato and whole spices' },

  // ===== CHICKEN THALI =====
  { id: 'cthali-001', category: 'CHICKEN_THALI', price: 180, is_veg: false, is_available: true,
    image_url: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=400&q=80',
    name_mr: 'चिकन मसाला थाळी', name_en: 'Chicken Masala Thali',
    description_mr: 'चिकन मसाला, भात, रोटी, वरण आणि सलाड',
    description_en: 'Chicken masala with rice, roti, dal and salad' },
  { id: 'cthali-002', category: 'CHICKEN_THALI', price: 180, is_veg: false, is_available: true,
    image_url: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=400&q=80',
    name_mr: 'चिकन धनगरी थाळी', name_en: 'Chicken Dhangari Thali',
    description_mr: 'धनगरी मसाल्याचे चिकन, भात, भाकरी, वरण',
    description_en: 'Chicken Dhangari style with rice, bhakri, dal' },
  { id: 'cthali-003', category: 'CHICKEN_THALI', price: 180, is_veg: false, is_available: true,
    image_url: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=400&q=80',
    name_mr: 'चिकन मालवणी थाळी', name_en: 'Chicken Malvani Thali',
    description_mr: 'मालवणी मसाल्याचे चिकन, भात, भाकरी, वरण',
    description_en: 'Chicken Malvani with rice, bhakri, dal' },
  { id: 'cthali-004', category: 'CHICKEN_THALI', price: 180, is_veg: false, is_available: true,
    image_url: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=400&q=80',
    name_mr: 'चिकन आळणी थाळी', name_en: 'Chicken Aalani Thali',
    description_mr: 'आळणी पद्धतीचे चिकन, भात, रोटी, वरण',
    description_en: 'Chicken Aalani style with rice, roti, dal' },
  { id: 'cthali-005', category: 'CHICKEN_THALI', price: 250, is_veg: false, is_available: true,
    image_url: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=400&q=80',
    name_mr: 'चिकन स्पेशल थाळी', name_en: 'Chicken Special Thali',
    description_mr: 'खास चिकन, भात, भाकरी, वरण, सोलकढी',
    description_en: 'Special chicken thali with rice, bhakri, dal, solkadhi' },
  { id: 'cthali-006', category: 'CHICKEN_THALI', price: 250, is_veg: false, is_available: true,
    image_url: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=400&q=80',
    name_mr: 'चिकन गावरान थाळी', name_en: 'Chicken Gavran Thali',
    description_mr: 'गावरान चिकन, भात, भाकरी, वरण आणि सलाड',
    description_en: 'Country chicken thali with rice, bhakri, dal' },
  { id: 'cthali-007', category: 'CHICKEN_THALI', price: 300, is_veg: false, is_available: true,
    image_url: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=400&q=80',
    name_mr: 'चिकन गावरान स्पेशल थाळी', name_en: 'Chicken Gavran Special Thali',
    description_mr: 'खास गावरान चिकन, भात, भाकरी, वरण, ताक',
    description_en: 'Premium Gavran chicken thali with rice, bhakri, dal, buttermilk' },

  // ===== MUTTON THALI =====
  { id: 'mthali-001', category: 'MUTTON_THALI', price: 300, is_veg: false, is_available: true,
    image_url: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d6?w=400&q=80',
    name_mr: 'मटण मसाला थाळी', name_en: 'Mutton Masala Thali',
    description_mr: 'मटण मसाला, भात, भाकरी, वरण आणि सलाड',
    description_en: 'Mutton masala with rice, bhakri, dal and salad' },
  { id: 'mthali-002', category: 'MUTTON_THALI', price: 300, is_veg: false, is_available: true,
    image_url: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d6?w=400&q=80',
    name_mr: 'मटण मालवणी थाळी', name_en: 'Mutton Malvani Thali',
    description_mr: 'मालवणी मसाल्याचे मटण, भात, भाकरी, वरण',
    description_en: 'Mutton Malvani with rice, bhakri, dal' },
  { id: 'mthali-003', category: 'MUTTON_THALI', price: 300, is_veg: false, is_available: true,
    image_url: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d6?w=400&q=80',
    name_mr: 'मटण घरगुती थाळी', name_en: 'Mutton Homemade Thali',
    description_mr: 'घरगुती मसाल्याचे मटण, भात, भाकरी, वरण, ताक',
    description_en: 'Home-style mutton with rice, bhakri, dal, buttermilk' },
  { id: 'mthali-004', category: 'MUTTON_THALI', price: 300, is_veg: false, is_available: true,
    image_url: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d6?w=400&q=80',
    name_mr: 'मटण धनगरी थाळी', name_en: 'Mutton Dhangari Thali',
    description_mr: 'धनगरी मसाल्याचे मटण, भात, भाकरी, वरण',
    description_en: 'Mutton Dhangari style with rice, bhakri, dal' },
  { id: 'mthali-005', category: 'MUTTON_THALI', price: 350, is_veg: false, is_available: true,
    image_url: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d6?w=400&q=80',
    name_mr: 'मटण स्पेशल थाळा', name_en: 'Mutton Special Thali',
    description_mr: 'खास मटण, भात, भाकरी, वरण, ताक, सोलकढी',
    description_en: 'Premium mutton thali with rice, bhakri, dal, buttermilk, solkadhi' },
  { id: 'mthali-006', category: 'MUTTON_THALI', price: 300, is_veg: false, is_available: true,
    image_url: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d6?w=400&q=80',
    name_mr: 'मटण आळणी थाळी', name_en: 'Mutton Aalani Thali',
    description_mr: 'आळणी पद्धतीचे मटण, भात, भाकरी, वरण',
    description_en: 'Mutton Aalani style with rice, bhakri, dal' },
  { id: 'mthali-007', category: 'MUTTON_THALI', price: 200, is_veg: false, is_available: true,
    image_url: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d6?w=400&q=80',
    name_mr: 'वजडी थाळी', name_en: 'Wajadi Thali',
    description_mr: 'मटणाचे वजड भाग, भात, भाकरी आणि वरण',
    description_en: 'Special thali with mutton cuts, rice, bhakri and dal' },

  // ===== HANDI =====
  { id: 'handi-001', category: 'HANDI', price: 330, is_veg: false, is_available: true,
    image_url: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=400&q=80',
    name_mr: 'चिकन हंडी', name_en: 'Chicken Handi',
    description_mr: 'हाफ ₹330 / फुल्ल ₹650 — मातीच्या हंडीत शिजवलेले चिकन',
    description_en: 'Half ₹330 / Full ₹650 — Slow-cooked chicken in clay handi' },
  { id: 'handi-002', category: 'HANDI', price: 330, is_veg: false, is_available: true,
    image_url: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=400&q=80',
    name_mr: 'चिकन मालवणी हंडी', name_en: 'Chicken Malvani Handi',
    description_mr: 'हाफ ₹330 / फुल्ल ₹650 — मालवणी मसाल्यात हंडीत चिकन',
    description_en: 'Half ₹330 / Full ₹650 — Chicken in Malvani masala, handi cooked' },
  { id: 'handi-003', category: 'HANDI', price: 330, is_veg: false, is_available: true,
    image_url: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=400&q=80',
    name_mr: 'चिकन घरगुती हंडी', name_en: 'Chicken Homemade Handi',
    description_mr: 'हाफ ₹330 / फुल्ल ₹650 — घरगुती मसाल्यात हंडीत चिकन',
    description_en: 'Half ₹330 / Full ₹650 — Home-style chicken handi' },
  { id: 'handi-004', category: 'HANDI', price: 320, is_veg: false, is_available: true,
    image_url: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=400&q=80',
    name_mr: 'चिकन धनगरी हंडी', name_en: 'Chicken Dhangari Handi',
    description_mr: 'हाफ ₹320 / फुल्ल ₹630 — धनगरी मसाल्यात हंडीत चिकन',
    description_en: 'Half ₹320 / Full ₹630 — Chicken Dhangari in handi' },
  { id: 'handi-005', category: 'HANDI', price: 320, is_veg: false, is_available: true,
    image_url: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=400&q=80',
    name_mr: 'चिकन कोल्हापुरी हंडी', name_en: 'Chicken Kolhapuri Handi',
    description_mr: 'हाफ ₹320 / फुल्ल ₹630 — कोल्हापूरी मसाल्यात हंडीत चिकन',
    description_en: 'Half ₹320 / Full ₹630 — Fiery Kolhapuri chicken in handi' },
  { id: 'handi-006', category: 'HANDI', price: 450, is_veg: false, is_available: true,
    image_url: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=400&q=80',
    name_mr: 'चिकन गावरान हंडी', name_en: 'Chicken Gavran Handi',
    description_mr: 'हाफ ₹450 / फुल्ल ₹800 — गावरान चिकन हंडीत धिम्या आचेवर',
    description_en: 'Half ₹450 / Full ₹800 — Country chicken slow-cooked in handi' },
  { id: 'handi-007', category: 'HANDI', price: 600, is_veg: false, is_available: true,
    image_url: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=400&q=80',
    name_mr: 'मटण हंडी', name_en: 'Mutton Handi',
    description_mr: 'हाफ ₹600 / फुल्ल ₹1150 — हंडीत धिम्या आचेवर शिजवलेले मटण',
    description_en: 'Half ₹600 / Full ₹1150 — Slow-cooked mutton in clay handi' },
  { id: 'handi-008', category: 'HANDI', price: 600, is_veg: false, is_available: true,
    image_url: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=400&q=80',
    name_mr: 'मटण मालवणी हंडी', name_en: 'Mutton Malvani Handi',
    description_mr: 'हाफ ₹600 / फुल्ल ₹1150 — मालवणी मसाल्यात हंडीत मटण',
    description_en: 'Half ₹600 / Full ₹1150 — Mutton Malvani in handi' },
  { id: 'handi-009', category: 'HANDI', price: 600, is_veg: false, is_available: true,
    image_url: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=400&q=80',
    name_mr: 'मटण घरगुती हंडी', name_en: 'Mutton Homemade Handi',
    description_mr: 'हाफ ₹600 / फुल्ल ₹1150 — घरगुती मसाल्यात हंडीत मटण',
    description_en: 'Half ₹600 / Full ₹1150 — Home-style mutton handi' },
  { id: 'handi-010', category: 'HANDI', price: 600, is_veg: false, is_available: true,
    image_url: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=400&q=80',
    name_mr: 'मटण धनगरी हंडी', name_en: 'Mutton Dhangari Handi',
    description_mr: 'हाफ ₹600 / फुल्ल ₹1150 — धनगरी मसाल्यात हंडीत मटण',
    description_en: 'Half ₹600 / Full ₹1150 — Mutton Dhangari in handi' },
  { id: 'handi-011', category: 'HANDI', price: 600, is_veg: false, is_available: true,
    image_url: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=400&q=80',
    name_mr: 'मटण कोल्हापुरी हंडी', name_en: 'Mutton Kolhapuri Handi',
    description_mr: 'हाफ ₹600 / फुल्ल ₹1150 — कोल्हापूरी मसाल्यात हंडीत मटण',
    description_en: 'Half ₹600 / Full ₹1150 — Fiery Kolhapuri mutton in handi' },

  // ===== EGG =====
  { id: 'egg-001', category: 'EGG', price: 150, is_veg: false, is_available: true,
    image_url: 'https://images.unsplash.com/photo-1482049016688-2d3e1b311543?w=400&q=80',
    name_mr: 'अंडा मसाला थाळी', name_en: 'Egg Masala Thali',
    description_mr: 'अंडा मसाला, भात, रोटी, वरण आणि सलाड',
    description_en: 'Egg masala with rice, roti, dal and salad' },
  { id: 'egg-002', category: 'EGG', price: 140, is_veg: false, is_available: true,
    image_url: 'https://images.unsplash.com/photo-1482049016688-2d3e1b311543?w=400&q=80',
    name_mr: 'अंडा करी थाळी', name_en: 'Egg Curry Thali',
    description_mr: 'अंडा करी, भात, रोटी, वरण आणि सलाड',
    description_en: 'Egg curry with rice, roti, dal and salad' },
  { id: 'egg-003', category: 'EGG', price: 170, is_veg: false, is_available: true,
    image_url: 'https://images.unsplash.com/photo-1482049016688-2d3e1b311543?w=400&q=80',
    name_mr: 'अंडा मखनवाला थाळी', name_en: 'Egg Butter Thali',
    description_mr: 'बटर मखनवाला अंडा, भात, रोटी, वरण',
    description_en: 'Egg in butter-makhani gravy with rice, roti, dal' },
  { id: 'egg-004', category: 'EGG', price: 150, is_veg: false, is_available: true,
    image_url: 'https://images.unsplash.com/photo-1482049016688-2d3e1b311543?w=400&q=80',
    name_mr: 'अंडा धनगरी थाळी', name_en: 'Egg Dhangari Thali',
    description_mr: 'धनगरी मसाल्यात शिजवलेले अंडे, भात, रोटी',
    description_en: 'Egg in Dhangari style with rice, roti and salad' },

  // ===== RICE =====
  { id: 'rice-001', category: 'RICE', price: 60, is_veg: true, is_available: true,
    image_url: 'https://images.unsplash.com/photo-1536304993881-ff86e0c9e6d7?w=400&q=80',
    name_mr: 'प्लेन राईस', name_en: 'Plain Rice',
    description_mr: 'हाफ ₹60 / फुल्ल ₹120 — ताजा शिजवलेला मऊ भात',
    description_en: 'Half ₹60 / Full ₹120 — Freshly cooked steamed rice' },
  { id: 'rice-002', category: 'RICE', price: 70, is_veg: true, is_available: true,
    image_url: 'https://images.unsplash.com/photo-1536304993881-ff86e0c9e6d7?w=400&q=80',
    name_mr: 'जरा राईस', name_en: 'Jeera Rice',
    description_mr: 'हाफ ₹70 / फुल्ल ₹130 — जिऱ्याच्या तडक्यासह सुगंधी भात',
    description_en: 'Half ₹70 / Full ₹130 — Fragrant jeera rice' },
  { id: 'rice-003', category: 'RICE', price: 200, is_veg: true, is_available: true,
    image_url: 'https://images.unsplash.com/photo-1536304993881-ff86e0c9e6d7?w=400&q=80',
    name_mr: 'डाळ खिचडी', name_en: 'Dal Khichdi',
    description_mr: 'मूगडाळ आणि भात एकत्र शिजवलेली पौष्टिक खिचडी',
    description_en: 'Comforting moong dal and rice with mild spices' },

  // ===== BREADS =====
  { id: 'bread-001', category: 'BREADS', price: 20, is_veg: true, is_available: true,
    image_url: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400&q=80',
    name_mr: 'प्लेन रोटी', name_en: 'Plain Roti',
    description_mr: 'गव्हाच्या पिठापासून बनवलेली मऊ रोटी',
    description_en: 'Soft whole wheat roti made to order' },
  { id: 'bread-002', category: 'BREADS', price: 30, is_veg: true, is_available: true,
    image_url: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400&q=80',
    name_mr: 'बटर रोटी', name_en: 'Butter Roti',
    description_mr: 'बटर लावलेली गरमागरम रोटी',
    description_en: 'Hot roti brushed with butter' },
  { id: 'bread-003', category: 'BREADS', price: 20, is_veg: true, is_available: true,
    image_url: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400&q=80',
    name_mr: 'भाकरी', name_en: 'Bhakri',
    description_mr: 'ज्वारी किंवा बाजरीच्या पिठापासून पारंपारिक भाकरी',
    description_en: 'Traditional bhakri from jowar or bajra flour' },
  { id: 'bread-004', category: 'BREADS', price: 20, is_veg: true, is_available: true,
    image_url: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400&q=80',
    name_mr: 'चपाती', name_en: 'Chapati',
    description_mr: 'गव्हाच्या पिठापासून बनवलेली ताजी चपाती',
    description_en: 'Soft fresh whole wheat chapati' },
  { id: 'bread-005', category: 'BREADS', price: 20, is_veg: true, is_available: true,
    image_url: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400&q=80',
    name_mr: 'पराटा', name_en: 'Paratha',
    description_mr: 'तेलावर भाजलेला लुसलुशीत पराटा',
    description_en: 'Flaky layered paratha cooked on a griddle' },

  // ===== OTHERS =====
  { id: 'other-001', category: 'OTHERS', price: 40, is_veg: true, is_available: true,
    image_url: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=400&q=80',
    name_mr: 'पापड', name_en: 'Papad',
    description_mr: 'कुरकुरीत भाजलेला पापड',
    description_en: 'Crispy roasted papad' },
  { id: 'other-002', category: 'OTHERS', price: 30, is_veg: true, is_available: true,
    image_url: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=400&q=80',
    name_mr: 'फ्राय पापड', name_en: 'Fry Papad',
    description_mr: 'तेलात तळलेला कुरकुरीत पापड',
    description_en: 'Crispy deep-fried papad' },
];

export function getItemName(item: MenuItem, lang: Language): string {
  return item[`name_${lang}` as `name_${Language}`] ?? item.name_en;
}

export function getItemDescription(item: MenuItem, lang: Language): string {
  return item[`description_${lang}` as `description_${Language}`] ?? item.description_en;
}
